services:

  mysql:
    image: mysql:8.0
    container_name: mysql-container

    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: local_DB

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql


  app:
    build: .
    container_name: spring-student-app

    ports:
      - "9090:9090"

    depends_on:
      - mysql

volumes:
  mysql-data: