spring.datasource.url=jdbc:mysql://${root}:${LpXTbuBtoRsOCeFItojwPlJcWOMFCYhF}@${{RAILWAY_PRIVATE_DOMAIN}}:3306/${railway}
spring.datasource.username=root
spring.datasource.password=LpXTbuBtoRsOCeFItojwPlJcWOMFCYhF
spring.jpa.hibernate.ddl-auto=update


developer.name=Mehul Raj
developer.role=Java Backend Developer