secret_key=${SECRET_KEY}
spring.application.name=student

spring.datasource.url=${MYSQL_URL_PROD}
spring.datasource.username=${MYSQL_USERNAME_PROD}
spring.datasource.password=${MYSQL_PASSWORD_PROD}
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=${MULTIPART_MAX}
spring.servlet.multipart.max-request-size=${MULTIPART_MAX_REQUEST}
file.upload-dir=${UPLOAD_DIR}

developer.name=Mehul Raj
developer.role=Java Backend Developer