spring.application.name=student
server.port=${SERVER_PORT}

secret_key=${SECRET_KEY}

spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}

spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=${MULTIPART_MAX}
spring.servlet.multipart.max-request-size=${MULTIPART_MAX_REQUEST}

file.upload-dir=${UPLOAD_DIR}

server.error.include-stacktrace=never
server.error.include-message=never

developer.name=Mehul Raj
developer.role=Java Backend Developer

#spring.profiles.active=${ENV:dev}
#spring.cache.type=${CACHE_TYPE}
#spring.data.redis.host=${CACHE_HOST}
#spring.data.redis.port=${CACHE_PORT}
#spring.cache.cache-names=${CACHE_NAMES}